[database]
server = "192.168.12.17"
database = "MAMAKADSM_HASTAM"
username = "metasoft"
password = "Meta26.soft"
driver = "{ODBC Driver 17 for SQL Server}" # Sizin sisteminizdeki ODBC sürücüsüne göre değişebilir

[credentials]
admin = "12345"
user = ""
